spring:
  application:
    name: gateway

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
        path: /uaa/**
        url: http://auth-service:8080
        stripPrefix: false
        sensitiveHeaders:
    account-service:
        path: /accounts/**
        url: http://account-service:8080
        stripPrefix: false
        sensitiveHeaders:
    statistics-service:
        path: /statistics/**
        url: http://statistics-service:8080
        stripPrefix: false
        sensitiveHeaders:
    notification-service:
        path: /notifications/**
        url: http://notification-service:8080
        stripPrefix: false
        sensitiveHeaders:
